import { Exercise } from "@/types/labforge";

export interface GenerateExtraExercisesParams {
  mandatoryExercise: Exercise;
  count?: number;
  domain?: string;
}

/**
 * AI Service responsible for automatic generation of application-oriented extra exercises
 * when a faculty member publishes a mandatory exercise.
 */
export class AIService {
  /**
   * Generates application-oriented extra exercises derived from a parent mandatory exercise.
   * Validates generated content, checks for duplicates, and sets parent references.
   */
  public async generateExtraExercises(params: GenerateExtraExercisesParams): Promise<Exercise[]> {
    const { mandatoryExercise, count = 2, domain = "Real-World Systems" } = params;
    
    // Simulate lightweight delay for AI synthesis
    await new Promise((resolve) => setTimeout(resolve, 800));

    const generatedExercises: Exercise[] = [];

    for (let i = 1; i <= count; i++) {
      const generatedId = `${mandatoryExercise.id}-ai-extra-${i}-${Date.now()}`;
      
      const newTitle = this.createApplicationTitle(mandatoryExercise.topic, domain, i);
      const newDescription = `Application-oriented extra practice derived from "${mandatoryExercise.title}". Apply ${mandatoryExercise.learningObjective} to solve domain challenges in ${domain}.`;
      
      // Duplicate check simulation
      if (this.isDuplicate(newTitle, mandatoryExercise)) {
        continue;
      }

      const extraExercise: Exercise = {
        id: generatedId,
        labId: mandatoryExercise.labId,
        semester: mandatoryExercise.semester,
        title: newTitle,
        topic: `${mandatoryExercise.topic} (${domain})`,
        difficulty: mandatoryExercise.difficulty === "Easy" ? "Medium" : "Hard",
        status: "not-started",
        timeEstimate: `${parseInt(mandatoryExercise.timeEstimate) + 10} min`,
        question: `Solve an applied problem based on ${mandatoryExercise.title} in the context of ${domain}.`,
        description: newDescription,
        learningObjective: `Apply knowledge of ${mandatoryExercise.topic} to solve practical ${domain} scenarios.`,
        constraints: mandatoryExercise.constraints || "Strict execution time limit: 2.0s.",
        examples: [
          {
            input: `// Sample ${mandatoryExercise.topic} input for ${domain}`,
            output: `// Verified expected ${domain} analytics output`,
            explanation: `Application output generated automatically based on parent exercise #${mandatoryExercise.id}.`
          }
        ],
        testCases: [
          {
            id: `tc-gen-${i}-1`,
            input: `test_input_${i}`,
            expectedOutput: `verified_output_${i}`
          }
        ],
        hints: [
          `This exercise was automatically generated by AI to expand your practical skills in ${domain}.`,
          `Reference parent exercise: "${mandatoryExercise.title}" for underlying syntax and patterns.`
        ],
        isMandatory: false,
        isAiGenerated: true,
        parentExerciseId: mandatoryExercise.id,
        createdAt: new Date().toISOString()
      };

      generatedExercises.push(extraExercise);
    }

    return generatedExercises;
  }

  private createApplicationTitle(topic: string, domain: string, index: number): string {
    const templates = [
      `${domain}: ${topic} Data Pipeline`,
      `Applied ${topic} in ${domain}`,
      `Advanced ${domain} ${topic} Challenge`,
    ];
    return templates[(index - 1) % templates.length];
  }

  private isDuplicate(title: string, parent: Exercise): boolean {
    return title.toLowerCase() === parent.title.toLowerCase();
  }
}

export const aiService = new AIService();
