import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { ObjectId } from "mongodb";
import { getDb } from "../db/mongodb";

export interface TriggerAiParams {
  mandatoryExerciseId: string;
  labId: string;
  facultyId: string;
  topic: string;
  objective: string;
  difficulty: "Easy" | "Medium" | "Hard";
  title: string;
}

export async function triggerAiExtraExerciseGeneration(params: TriggerAiParams) {
  const db = await getDb();
  const parentId = new ObjectId(params.mandatoryExerciseId);
  const labIdObj = new ObjectId(params.labId);
  const facultyIdObj = new ObjectId(params.facultyId);

  // Idempotence check: return existing generated extras if already present
  const existingExtras = await db
    .collection("exercises")
    .find({ sourceExerciseId: parentId, type: "extra" })
    .toArray();

  if (existingExtras.length > 0) {
    return existingExtras.map((e) => ({
      id: e._id.toString(),
      title: e.title,
      topic: e.topic,
      difficulty: e.difficulty,
    }));
  }

  // Synthesize 2 application-oriented extra exercises
  const extraTemplates = [
    {
      title: `Application Challenge: ${params.topic} System Implementation`,
      topic: `${params.topic} (Real-World Application)`,
      difficulty: params.difficulty === "Easy" ? "Medium" : "Hard",
      question: `Implement a real-world software system scenario expanding on '${params.title}'.`,
      description: `Application-oriented extra practice exercise automatically generated by AI to deepen practical mastery of ${params.topic}.`,
      objective: `Apply ${params.objective} to real-world domain engineering scenarios.`,
    },
    {
      title: `Advanced Performance Optimization: ${params.topic}`,
      topic: `${params.topic} (Optimization & Edge Cases)`,
      difficulty: "Hard",
      question: `Optimize data structures and memory layout for '${params.title}' under high load.`,
      description: `Advanced extra practice exercise generated by AI to test edge-case handling and performance limits.`,
      objective: `Optimize complexity and handle edge cases for ${params.topic}.`,
    },
  ];

  const createdExtras = [];

  for (let i = 0; i < extraTemplates.length; i++) {
    const tmpl = extraTemplates[i];

    // Duplicate check in database
    const duplicate = await db.collection("exercises").findOne({
      laboratoryId: labIdObj,
      title: tmpl.title,
    });

    if (duplicate) continue;

    const extraDoc = {
      exerciseNumber: 100 + i + 1,
      title: tmpl.title,
      question: tmpl.question,
      description: tmpl.description,
      examples: [
        {
          input: `// Sample input for ${tmpl.title}`,
          output: `// Expected application output`,
          explanation: `Generated based on parent exercise #${params.mandatoryExerciseId}`,
        },
      ],
      constraints: "Strict runtime limit 2.0s. Memory limit 64MB.",
      testCases: [
        { id: `extra-tc-${i + 1}`, input: "app_input", expectedOutput: "app_output" },
      ],
      laboratoryId: labIdObj,
      semesterNumber: 5,
      createdBy: facultyIdObj,
      type: "extra" as const,
      status: "published" as const,
      difficulty: tmpl.difficulty as any,
      topic: tmpl.topic,
      objective: tmpl.objective,
      hints: [
        `This extra practice exercise was automatically generated by AI to expand on '${params.title}'.`,
        `Reference parent exercise #${params.mandatoryExerciseId} for underlying algorithms.`,
      ],
      sourceExerciseId: parentId,
      aiGenerationStatus: "completed" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    const res = await db.collection("exercises").insertOne(extraDoc);
    createdExtras.push({
      id: res.insertedId.toString(),
      title: tmpl.title,
      topic: tmpl.topic,
      difficulty: tmpl.difficulty,
    });
  }

  return createdExtras;
}
