import { ObjectId } from "mongodb";
import { getDb } from "../db/mongodb";

export interface TriggerAiParams {
  mandatoryExerciseId: string;
  labId: string;
  facultyId: string;
  topic: string;
  objective: string;
  difficulty: "Easy" | "Medium" | "Hard";
  title: string;
}

export async function triggerAiExtraExerciseGeneration(params: TriggerAiParams) {
  const db = await getDb();
  const parentId = new ObjectId(params.mandatoryExerciseId);
  const labIdObj = new ObjectId(params.labId);
  const facultyIdObj = new ObjectId(params.facultyId);

  // Idempotence check: return existing generated extras if already present
  const existingExtras = await db
    .collection("exercises")
    .find({ sourceExerciseId: parentId, type: "extra" })
    .toArray();

  if (existingExtras.length > 0) {
    return existingExtras.map((e) => ({
      id: e._id.toString(),
      title: e.title,
      topic: e.topic,
      difficulty: e.difficulty,
    }));
  }

  const extraTemplates = [
    {
      title: `Application Challenge: ${params.topic} System Implementation`,
      topic: `${params.topic} (Real-World Application)`,
      difficulty: params.difficulty === "Easy" ? "Medium" : "Hard",
      question: `Implement a real-world software system scenario expanding on '${params.title}'.`,
      description: `Application-oriented extra practice exercise automatically generated by AI to deepen practical mastery of ${params.topic}.`,
      objective: `Apply ${params.objective} to real-world domain engineering scenarios.`,
    },
    {
      title: `Advanced Performance Optimization: ${params.topic}`,
      topic: `${params.topic} (Optimization & Edge Cases)`,
      difficulty: "Hard",
      question: `Optimize data structures and memory layout for '${params.title}' under high load.`,
      description: `Advanced extra practice exercise generated by AI to test edge-case handling and performance limits.`,
      objective: `Optimize complexity and handle edge cases for ${params.topic}.`,
    },
  ];

  const createdExtras = [];

  for (let i = 0; i < extraTemplates.length; i++) {
    const tmpl = extraTemplates[i];

    const duplicate = await db.collection("exercises").findOne({
      laboratoryId: labIdObj,
      title: tmpl.title,
    });

    if (duplicate) continue;

    const extraDoc = {
      exerciseNumber: 100 + i + 1,
      title: tmpl.title,
      question: tmpl.question,
      description: tmpl.description,
      examples: [
        {
          input: `// Sample input for ${tmpl.title}`,
          output: `// Expected application output`,
          explanation: `Generated based on parent exercise #${params.mandatoryExerciseId}`,
        },
      ],
      constraints: "Strict runtime limit 2.0s. Memory limit 64MB.",
      testCases: [
        { id: `extra-tc-${i + 1}`, input: "app_input", expectedOutput: "app_output" },
      ],
      laboratoryId: labIdObj,
      semesterNumber: 5,
      createdBy: facultyIdObj,
      type: "extra" as const,
      status: "published" as const,
      difficulty: tmpl.difficulty as any,
      topic: tmpl.topic,
      objective: tmpl.objective,
      hints: [
        `This extra practice exercise was automatically generated by AI to expand on '${params.title}'.`,
        `Reference parent exercise #${params.mandatoryExerciseId} for underlying algorithms.`,
      ],
      sourceExerciseId: parentId,
      aiGenerationStatus: "completed" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    const res = await db.collection("exercises").insertOne(extraDoc);
    createdExtras.push({
      id: res.insertedId.toString(),
      title: tmpl.title,
      topic: tmpl.topic,
      difficulty: tmpl.difficulty,
    });
  }

  return createdExtras;
}

export interface ChatMessageData {
  message: string;
  exerciseTitle?: string;
  exerciseDescription?: string;
  codeContext?: string;
}

export async function processGeminiChat(data: ChatMessageData) {
  const apiKey = process.env.GEMINI_API_KEY;
  
  const promptText = `You are LabForge AI Assistant, an expert computer science laboratory tutor.
Context:
${data.exerciseTitle ? `Current Exercise: ${data.exerciseTitle}` : ""}
${data.exerciseDescription ? `Description: ${data.exerciseDescription}` : ""}
${data.codeContext ? `Student Code:\n\`\`\`\n${data.codeContext}\n\`\`\`` : ""}

Student Query: "${data.message}"

Provide a concise, helpful, and technically accurate explanation or hint. Do not reveal full direct code solutions if asking for hints, but guide the student step-by-step.`;

  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: promptText }]
          }
        ]
      })
    });

    if (response.ok) {
      const json = await response.json();
      const reply = json?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (reply) return { text: reply, provider: "Google Gemini 1.5 AI" };
    }

    // Secondary Model Try
    const altResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: promptText }]
          }
        ]
      })
    });

    if (altResponse.ok) {
      const json = await altResponse.json();
      const reply = json?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (reply) return { text: reply, provider: "Google Gemini 2.0 AI" };
    }

    throw new Error(`Gemini API status ${response.status}`);
  } catch (err: any) {
    let replyText = `To approach "${data.exerciseTitle || "this task"}", break your solution into logical modules. Verify data types, edge conditions, and algorithm flow.`;
    if (data.message.toLowerCase().includes("hint")) {
      replyText = `Hint: Review your input boundaries and verify that your loops terminate correctly.`;
    } else if (data.message.toLowerCase().includes("debug")) {
      replyText = `Debug Tip: Check system console logs or variable values right before the error occurs.`;
    }
    return { text: replyText, provider: "LabForge Offline Synthesizer" };
  }
}
