/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacultyDashboardRouteImport } from './routes/faculty/dashboard'
import { Route as FacultyLabsRouteImport } from './routes/faculty/labs'
import { Route as FacultyLoginRouteImport } from './routes/faculty/login'
import { Route as FacultySemesterRouteImport } from './routes/faculty/semester'
import { Route as StudentLabsRouteImport } from './routes/student/labs'
import { Route as StudentLoginRouteImport } from './routes/student/login'
import { Route as StudentSemesterRouteImport } from './routes/student/semester'
import { Route as StudentWorkspaceRouteImport } from './routes/student/workspace'
import { Route as FacultyExercisesNewRouteImport } from './routes/faculty/exercises/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/faculty/dashboard',
  path: '/faculty/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyLabsRoute = FacultyLabsRouteImport.update({
  id: '/faculty/labs',
  path: '/faculty/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyLoginRoute = FacultyLoginRouteImport.update({
  id: '/faculty/login',
  path: '/faculty/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultySemesterRoute = FacultySemesterRouteImport.update({
  id: '/faculty/semester',
  path: '/faculty/semester',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLabsRoute = StudentLabsRouteImport.update({
  id: '/student/labs',
  path: '/student/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSemesterRoute = StudentSemesterRouteImport.update({
  id: '/student/semester',
  path: '/student/semester',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWorkspaceRoute = StudentWorkspaceRouteImport.update({
  id: '/student/workspace',
  path: '/student/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyExercisesNewRoute = FacultyExercisesNewRouteImport.update({
  id: '/faculty/exercises/new',
  path: '/faculty/exercises/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/labs': typeof FacultyLabsRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/semester': typeof FacultySemesterRoute
  '/student/labs': typeof StudentLabsRoute
  '/student/login': typeof StudentLoginRoute
  '/student/semester': typeof StudentSemesterRoute
  '/student/workspace': typeof StudentWorkspaceRoute
  '/faculty/exercises/new': typeof FacultyExercisesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/labs': typeof FacultyLabsRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/semester': typeof FacultySemesterRoute
  '/student/labs': typeof StudentLabsRoute
  '/student/login': typeof StudentLoginRoute
  '/student/semester': typeof StudentSemesterRoute
  '/student/workspace': typeof StudentWorkspaceRoute
  '/faculty/exercises/new': typeof FacultyExercisesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/labs': typeof FacultyLabsRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/semester': typeof FacultySemesterRoute
  '/student/labs': typeof StudentLabsRoute
  '/student/login': typeof StudentLoginRoute
  '/student/semester': typeof StudentSemesterRoute
  '/student/workspace': typeof StudentWorkspaceRoute
  '/faculty/exercises/new': typeof FacultyExercisesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faculty/dashboard'
    | '/faculty/labs'
    | '/faculty/login'
    | '/faculty/semester'
    | '/student/labs'
    | '/student/login'
    | '/student/semester'
    | '/student/workspace'
    | '/faculty/exercises/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faculty/dashboard'
    | '/faculty/labs'
    | '/faculty/login'
    | '/faculty/semester'
    | '/student/labs'
    | '/student/login'
    | '/student/semester'
    | '/student/workspace'
    | '/faculty/exercises/new'
  id:
    | '__root__'
    | '/'
    | '/faculty/dashboard'
    | '/faculty/labs'
    | '/faculty/login'
    | '/faculty/semester'
    | '/student/labs'
    | '/student/login'
    | '/student/semester'
    | '/student/workspace'
    | '/faculty/exercises/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyLabsRoute: typeof FacultyLabsRoute
  FacultyLoginRoute: typeof FacultyLoginRoute
  FacultySemesterRoute: typeof FacultySemesterRoute
  StudentLabsRoute: typeof StudentLabsRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentSemesterRoute: typeof StudentSemesterRoute
  StudentWorkspaceRoute: typeof StudentWorkspaceRoute
  FacultyExercisesNewRoute: typeof FacultyExercisesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/dashboard': {
      id: '/faculty/dashboard'
      path: '/faculty/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/labs': {
      id: '/faculty/labs'
      path: '/faculty/labs'
      fullPath: '/faculty/labs'
      preLoaderRoute: typeof FacultyLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/login': {
      id: '/faculty/login'
      path: '/faculty/login'
      fullPath: '/faculty/login'
      preLoaderRoute: typeof FacultyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/semester': {
      id: '/faculty/semester'
      path: '/faculty/semester'
      fullPath: '/faculty/semester'
      preLoaderRoute: typeof FacultySemesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/labs': {
      id: '/student/labs'
      path: '/student/labs'
      fullPath: '/student/labs'
      preLoaderRoute: typeof StudentLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/semester': {
      id: '/student/semester'
      path: '/student/semester'
      fullPath: '/student/semester'
      preLoaderRoute: typeof StudentSemesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/workspace': {
      id: '/student/workspace'
      path: '/student/workspace'
      fullPath: '/student/workspace'
      preLoaderRoute: typeof StudentWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/exercises/new': {
      id: '/faculty/exercises/new'
      path: '/faculty/exercises/new'
      fullPath: '/faculty/exercises/new'
      preLoaderRoute: typeof FacultyExercisesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyLabsRoute: FacultyLabsRoute,
  FacultyLoginRoute: FacultyLoginRoute,
  FacultySemesterRoute: FacultySemesterRoute,
  StudentLabsRoute: StudentLabsRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentSemesterRoute: StudentSemesterRoute,
  StudentWorkspaceRoute: StudentWorkspaceRoute,
  FacultyExercisesNewRoute: FacultyExercisesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
